services:
  web:
    build: .
    container_name: domu_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/domu_db
    depends_on:
      - db
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:13
    container_name: domu_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: domu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
