services:
  web:
    build: .
    container_name: domu_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/domu_db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:16
    container_name: domu_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: domu_db
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d domu_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
